name: SSH via Tailscale

on:
  workflow_call:
    inputs:
      command:
        description: Command to run on the remote server.
        required: false
        type: string
        default: hostname && whoami && pwd
    secrets:
      TAILSCALE_AUTHKEY:
        required: true
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USER:
        required: true
      SSH_PASS:
        required: true
  workflow_dispatch:
    inputs:
      command:
        description: Command to run on the remote server.
        required: false
        type: string
        default: hostname && whoami && pwd

jobs:
  ssh:
    name: SSH via Tailscale
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH via Tailscale
        uses: ./.github/actions/ssh-tailscale
        with:
          command: ${{ inputs.command }}
          tailscale_authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_pass: ${{ secrets.SSH_PASS }}
