name: Test SSH via Tailscale

on:
  workflow_dispatch:

jobs:
  echo:
    name: Echo on remote server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo via SSH
        uses: ./.github/actions/ssh-tailscale
        with:
          command: |
            echo "hello from github actions via tailscale"
            echo "hostname: $(hostname)"
            echo "user: $(whoami)"
            echo "current directory: $(pwd)"
            echo "hello from github actions via tailscale" >> /tmp/test-nnh.log
          tailscale_authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_pass: ${{ secrets.SSH_PASS }}
