name: Test SSH via Tailscale

on:
  workflow_dispatch:

jobs:
  echo:
    name: Echo on remote server
    uses: ./.github/workflows/ssh-tailscale.yml
    with:
      command: |
        echo "hello from github actions via tailscale"
        echo "hostname: $(hostname)"
        echo "user: $(whoami)"
        echo "current directory: $(pwd)"
        echo "hello from github actions via tailscale" >> /tmp/test-nnh.log
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASS: ${{ secrets.SSH_PASS }}
